### ISSUE TITLE
In group.go, why does the the Groups type contains Groups?

### ISSUE THREAD

**Issue by juddernaught** [jarias/stormpath-sdk-go#10]
There's a type called Groups, but unlike the type Applications in Application.go, it contains a slice of Groups, instead of Groups. Looking at the tests for Groups, nothing does assertions on what Groups contains,  which is why it may never have been caught. `
type Groups struct {
	list
	Items []Groups
}
`

Is this intentional or not? Happy to put a pull request in!

**Comment by jarias** [comment]
That looks like a bug, good catch feel free to send a pull request make sure to check the contributing section in the REAMDE.
