### ISSUE TITLE
RegisterAccount in application.go just returns error

### ISSUE THREAD

**Issue by juddernaught** [jarias/stormpath-sdk-go#11]
It doesn't appear that RegisterAccount in application.go modifies the pointer to the account, which means that after registering account, you need to authenticate to get access to the Account struct which includes the Href and other details that get created server side after registering which is useful for things later on like assigning groups, etc. 

Again, happy to submit a pr if this make sense.

**Comment by jarias** [comment]
It actually does look at https://github.com/jarias/stormpath-sdk-go/blob/master/application.go#L125 and https://github.com/jarias/stormpath-sdk-go/blob/master/stormpath.go#L83 The same pointer is pass the the body and the result.

**Comment by juddernaught** [comment]
Makes sense. Thanks!
