### ISSUE TITLE
Implement OAuth Endpoints

### ISSUE THREAD

**Issue by jarias** [jarias/stormpath-sdk-go#15]
See https://docs.stormpath.com/guides/token-management/

Tasks:

* [ ] ~~Get an OAuth token~~
* [ ] ~~Configure the OAuth policy in the application~~
* [ ] ~~List access tokens~~
* [ ] ~~Validate tokens~~
* [ ] ~~Refresh token~~
* [ ] ~~Revoke token~~

**Comment by andrehjr** [comment]
Hello @jarias! any progress on this? If not, I can take a look at it

**Comment by jarias** [comment]
I've work a bit on it I can upload the branch if you want to help out.

**Comment by jarias** [comment]
https://github.com/jarias/stormpath-sdk-go/tree/oauth

**Comment by andrehjr** [comment]
Will take a look into it, Thanks! I'm currently in need of this for a project :)

**Comment by ax-nathan** [comment]
@jarias, my company is starting to use stormpath-sdk-go. We would like to complete this feature. Would you be open to a PR?

**Comment by jarias** [comment]
@ax-nathan sure thing I having been able to spend a lot of time on the SDK lately, glad to get some help. 

There is a branch already in place https://github.com/jarias/stormpath-sdk-go/tree/oauth the ValidateToken is already in the development branch

**Comment by ax-nathan** [comment]
Sounds good, @jarias. We'll work on it...

**Comment by jarias** [comment]
@ax-nathan I just finish all the remaining tasks :) doing a release soon.
