### ISSUE TITLE
Client GET requests errantly signing and sending a payload of "" (double-quotes)

### ISSUE THREAD

**Issue by sappenin** [jarias/stormpath-sdk-go#23]
Hi, I'm trying to adapt your library to work inside of the the Google App Engine runtime for GO.  

One issue I ran into is that stormpath.go#newRequest (see line ~115) attempts to encode any payload (even empty payloads) as JSON.  For GET requests with no payload, this yields a string containing two quotation marks.

This two-quote payload then gets signed inside of sauthc1.go, and is sent along to the server.  Normally, the go http client will send this payload along, and everything works fine while communicating with Stormpath.  However, inside of appengine, the native http client is not permitted.  Instead, we must use the urlFetch service, and this service seems to strip out the payload for GET requests.

The net effect is that the sauthc1 signature always fails inside of StormPath because the signature is computed with a payload of "", but the actual request coming from AppEngine has no such payload.

One way I've gotten around this is to add an extra "if" condition in stormpath#newRequest to simply set the body to "body.([]byte)" if the method is GET.

Without this change, this feels like a bug in the client (IMHO).  GET requests generally shouldn't have a payload.

What do you think?

**Comment by jarias** [comment]
@sappenin Sorry for the late response, I think it makes sense, if you want you can send a PR if you have the time.

**Comment by jarias** [comment]
Any luck with this? I've been looking at the Stormpath ref impl of the SAuthc1 that they its use in their backend to validate the signature ant if there is not content in the request it would actually sing an empty Java string as the body, So your scenario should actually work, the Go SDK actually signs and empty []byte{} which is the same as []byte("") see https://play.golang.org/p/LmQq5IeAB8

```java
protected String getRequestPayloadWithoutQueryParams(Request request) {
        try {
            InputStream content = request.getBody();
            if (content == null) return "";

            if (content instanceof StringInputStream) {
                return content.toString();
            }

            if (!content.markSupported()) {
                throw new RequestAuthenticationException("Unable to read request payload to authenticate request (mark not supported).");
            }

            content.mark(-1);

            //convert InputStream into a String in one shot:
            String string;
            try {
                string = new Scanner(content, "UTF-8").useDelimiter("\\A").next();
            } catch (NoSuchElementException nsee) {
                string = "";
            }
            //BAM!  That just happened.

            content.reset();

            return string;

        } catch (Exception e) {
            throw new RequestAuthenticationException("Unable to read request payload to authenticate request: " + e.getMessage(), e);
        }
    }
```

You could extract the header Stormpath-Request-Id of a sample response and I can tell the eng team at stormpath to help me track the exact issue.

**Comment by jarias** [comment]
Actually found the real culprit, now I see what you where saying if the content type of the request is JSON which is all the requests except the OAuth endpoint even if the method was a get the empty []byte was been marshaled into JSON causing the issue.

I got a fix for it and would be pushing it shortly.
