### ISSUE TITLE
Nil responsees result in a panic `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by pengux** [jarias/stormpath-sdk-go#24]
When a request results in a nil response it creates a panic in `stormpath-sdk-go.handleResponseError` as there is no nil-check for `resp`

**Comment by jarias** [comment]
@pengux I've seen this happen, haven't got the time to work it out, if you can provide the code you where using to create a test case that would be really helpful, also PRs are more than welcome.

**Comment by pengux** [comment]
@jarias Will try to create a PR
