### ISSUE TITLE
Cannot update custom data with Account.UpdateCustomData

### ISSUE THREAD

**Issue by pengux** [jarias/stormpath-sdk-go#25]
The error is `Post /customData: unsupported protocol scheme ""`

**Comment by jarias** [comment]
@pengux can you provide the full example code

Thanks.

**Comment by pengux** [comment]
@jarias Will work to fix the issue

**Comment by pengux** [comment]
The problem occur when the account has an empty `href` value, so refreshing it with data from Stormpath before updating with `UpdateCustomData` will fix the issue
