### ISSUE TITLE
Missing Delete method for Account

### ISSUE THREAD

**Issue by pengux** [jarias/stormpath-sdk-go#28]
The REST API endpoint: https://docs.stormpath.com/rest/product-guide/latest/reference.html#delete-an-account

**Comment by pengux** [comment]
Found out that there is a Delete method on `resource` that seems to work for Account too, but it's not documented in [godoc](https://godoc.org/github.com/jarias/stormpath-sdk-go).

**Comment by jarias** [comment]
@pengux the problem is that resource is private type, that's why its public methods don't show in godoc, I could probably make it public just to have a more clear documentation, I'm not familiar with the best practice around this issue.
