### ISSUE TITLE
Vendor deps

### ISSUE THREAD

**Issue by jarias** [jarias/stormpath-sdk-go#42]

**Comment by jxstanford** [comment]
glide is pretty handy for this.  I had to roll jwt-go back to v2.6.0 to get a step further in the web example.  going to file another issue ticket to see if you can help me understand why I still can't get that to work...

**Comment by jarias** [comment]
@jxstanford latest master has fixed JWT lib version set to v2 using gopkg.in

**Comment by jxstanford** [comment]
cool!
