### ISSUE TITLE
web example panic

### ISSUE THREAD

**Issue by jxstanford** [jarias/stormpath-sdk-go#45]
Any pointers would be helpful.  I was trying to run the web example, and have the following environment:

Go 1.6.2 on MacOSX 10.11.5
```
~/.stormpath/stormpath.yaml
---
stormpath:
  client:
    apiKey:
      id: "XXXXX"
      secret: "YYYYY"
  application:
    name: "GSK"
    href: "https://api.stormpath.com/v1/applications/2qkEiSjJBR3cE8ALRnBxgg"
```

Steps:

`cd web/example`
`go run example.go`

Output:

```
ERROR: 2016/06/17 11:16:26 viper.go:1034: svType != tvType; key=name, st=string, tt=<nil>, sv=GSK, tv=<nil>
ERROR: 2016/06/17 11:16:26 viper.go:1034: svType != tvType; key=href, st=string, tt=<nil>, sv=https://api.stormpath.com/v1/applications/2qkEiSjJBR3cE8ALRnBxgg, tv=<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x12ad68]

goroutine 1 [running]:
panic(0x552260, 0xc82000a100)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/jarias/stormpath-sdk-go/web.resolveAccountStores(0xc8204a0640)
	/Users/stanford/devel/go_workspace/src/github.com/jarias/stormpath-sdk-go/web/web.go:110 +0x1c8
github.com/jarias/stormpath-sdk-go/web.NewStormpathMiddleware(0xd54348, 0xc820112ab0, 0xc8201108e0, 0x1, 0x1, 0x0)
	/Users/stanford/devel/go_workspace/src/github.com/jarias/stormpath-sdk-go/web/web.go:77 +0x18a
main.main()
	/Users/stanford/devel/go_workspace/src/github.com/jarias/stormpath-sdk-go/web/example/example.go:60 +0x141
exit status 2
```

**Comment by jarias** [comment]
Does your app has a default account store? If not the panic shouldn't happen, I'll check it out

**Comment by jarias** [comment]
@jxstanford Looks like the issue is in fact that your stormpath app doesn't have a default account store mapping, but the code was doing a wrong check, with PR #47 you would still panic since we cannot initialize according to spec if register is enabled and no default account store mapping is set, but with a better error message.

**Comment by jxstanford** [comment]
Pulled latest master.  Now when I set register to false in config/web.stormpath.yaml I still panic with:

panic: No default account store is mapped to the specified application. A default account store is required for registration.

**Comment by jarias** [comment]
@jxstanford Yeah you need to add a default account store mapping to your stormpath app, this can be done in the stormpath web console.

**Comment by jxstanford** [comment]
After adding a default account store, the server starts up.  When I browse to the page, there isn't a form to enter credentials for login or register, but more importantly, I can't figure out how to send a proper curl request to the login endpoint for an existing user.

Here's my scenario:

I have an account store named `Demo Customer 1` with an account in it.  I've tried several combinations of base64 encoded basic auth headers, but not luck passing it to `http://localhost:8080/login`.  I always get `{"accountStores":[],"form":{"fields":null}}` as a response.

**Comment by jarias** [comment]
Found and issue with how the user configuration was loaded that should fix the issue with disabling the resister endpoint.

As for your other question you might want to check out the stormpath spec to see how the web extension works. https://github.com/stormpath/stormpath-framework-spec

But here is the gist for the login

From the browser if you go to http://localhost:8080/login you should see a standard form login from curl or any other client if you don't specify the Accept header in case of a GET request it would return the JSON object that you are seeing, so SPA frameworks like Angular could render the login form according to how you configure it, it does seems strange that the fields element is null, I would look into it.

If you want to login via JSON (curl) you need to post a JSON object with `{"login": "USERNAME", "password": "PASSWORD"}`

Again all this is in the stormpath spec, if you got more questions let me know.

**Comment by jarias** [comment]
@jxstanford Can you paste your stormpath.yaml minus credentials to see why the fields element is null.

Thanks.

**Comment by jxstanford** [comment]
```
---
stormpath:
  client:
    apiKey:
      id: "XXXX"
      secret: "YYYY"
  application:
    name: "GSK"
    href: "https://api.stormpath.com/v1/applications/2qkEiSjJBR3cE8ALRnBxgg"
```

**Comment by jarias** [comment]
@jxstanford Found other config issues that might be causing you issues, hope to have them merge today

**Comment by jxstanford** [comment]
sounds good. thanks for the near-real-time response!

**Comment by jarias** [comment]
jeje no worries, I work as a contractor for Stormpath, and even though they don't officially support the Go SDK I like to keep the same quality support they have for their other integrations. ;)
