### ISSUE TITLE
Application.RegisterSocialAccount failes

### ISSUE THREAD

**Issue by jimzhan** [jarias/stormpath-sdk-go#5]
After retrieving the correct access token from github, I'm getting this:

```shell
stormpath.go:174: [ERROR] Oops! We encountered an unexpected error.  Please contact support and explain what you were doing at the time this error occurred.
```

Beside, can we have the detailed error code (stormpath) to do some further debugs?

**Comment by jarias** [comment]
Just added better log message for stormpath request errors

**Comment by jimzhan** [comment]
Tks for the prompt response, got the exact error re. the social account login (with user:email scope given from Github already): 

```shell
Stormpath is unable to create or update the account because the Github response did not contain the required 'email' property. ]
More info [ http://docs.stormpath.com/errors/7201
```

Seems the SDK does not send the metadata to Stormpath?

**Comment by jimzhan** [comment]
Can we also have detail request/respons HTTP log under debug mode (STORMPATH_LOG_LEVEL)?

**Comment by jarias** [comment]
I need to figure out the require data for a Github directory cause is not on the REST API docs only Facebook and Google. (at least I didn't found it)

As for the debug log I can work on that.

**Comment by jarias** [comment]
request/response dumps should appear if STORMPATH_LOG_LEVEL env variable is set to DEBUG

**Comment by jimzhan** [comment]
I've updated to beta8 & didn't c any detailed request/response logs re. external HTTP request, only the Stormpath, I suppose the outgoing request for Github is missing some kinda scope? I've also submitted an issue to Stormpath & they couldn't reproduce the issue, the correct response from Github should be like this:

```shell
{"access_token":"e73e16c7e42f292c6912e7710c838347ae178b4a", "scope":"repo,gist", "token_type":"bearer"}
```
